spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone
    username: postgres
    password: capstone
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


flyway:
  locations: classpath:db/migration

jwt:
  secret: "10b1c60213f53f6a83a0c4e48f59d5b2f80a4c3da5e38c49d96bacf9014dff6a"